site_name: Recipe Book
site_description: "Recipe collection"
site_author: "Alyona Belova"

theme:
  name: null
  custom_dir: theme

nav:
  - Home: index.md
  - Baking: baking.md
  - Main Courses: main-courses.md

markdown_extensions:
  - toc:
      toc_depth: 2
