name: Build and Deploy Site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      site-path: ./site
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Python dependencies
        run: pip install mkdocs
      - name: Install Node dependencies
        run: |
          npm install -g postcss postcss-cli autoprefixer cssnano html-minifier

  lint-and-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Build MkDocs site
        run: python -m mkdocs build

      - name: Validate HTML
        run: |
          html-validator-cli --file=site/index.html --verbose

      - name: Minify HTML
        run: |
          find site -name '*.html' -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;

      - name: Process CSS with PostCSS
        run: |
          npx postcss site/css/*.css --use autoprefixer cssnano -d site/css/

      - name: Minify JS
        run: |
          find site/js -name '*.js' -exec npx terser {} -o {} \;

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
